$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:6
        },
        1000:{
            items:9
        }
    }
})